# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Details_song.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Details_song(object):
    def setupUi(self, Details_song):
        Details_song.setObjectName("Details_song")
        Details_song.resize(800, 600)
        Details_song.setMinimumSize(QtCore.QSize(800, 600))
        Details_song.setMaximumSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Details_song)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(Details_song)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.Song_name = QtWidgets.QLabel(Details_song)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Song_name.setFont(font)
        self.Song_name.setObjectName("Song_name")
        self.verticalLayout.addWidget(self.Song_name)
        self.Album_name = QtWidgets.QLabel(Details_song)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Album_name.setFont(font)
        self.Album_name.setObjectName("Album_name")
        self.verticalLayout.addWidget(self.Album_name)
        self.Author_name = QtWidgets.QLabel(Details_song)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Author_name.setFont(font)
        self.Author_name.setObjectName("Author_name")
        self.verticalLayout.addWidget(self.Author_name)
        self.Lyrics = QtWidgets.QPushButton(Details_song)
        self.Lyrics.setObjectName("Lyrics")
        self.verticalLayout.addWidget(self.Lyrics)
        self.Return_to_results = QtWidgets.QPushButton(Details_song)
        self.Return_to_results.setObjectName("Return_to_results")
        self.verticalLayout.addWidget(self.Return_to_results)

        self.retranslateUi(Details_song)
        QtCore.QMetaObject.connectSlotsByName(Details_song)

    def retranslateUi(self, Details_song):
        _translate = QtCore.QCoreApplication.translate
        Details_song.setWindowTitle(_translate("Details_song", "Form"))
        self.label_6.setText(_translate("Details_song", "Details"))
        self.Song_name.setText(_translate("Details_song", "Song name: "))
        self.Album_name.setText(_translate("Details_song", "Album name"))
        self.Author_name.setText(_translate("Details_song", "Author name"))
        self.Lyrics.setText(_translate("Details_song", "Click to open lyrics"))
        self.Return_to_results.setText(_translate("Details_song", "Return to results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Details_song = QtWidgets.QWidget()
    ui = Ui_Details_song()
    ui.setupUi(Details_song)
    Details_song.show()
    sys.exit(app.exec_())
