#!/usr/bin/env python3

from PyQt5 import QtCore, QtGui, QtWidgets
from Login_ui import Ui_login as Login
from Filters_ui import Ui_Filters as Filters
from Result_ui import Ui_Result as Result
from Details_song_ui import Ui_Details_song as Details_song
from Lyrics_ui import Ui_Lyrics as Lyrics

class Controller:
    filters_exist = 0
    result_exist = 0
    login_exist = 0
    details_exist = 0
    def __init__(self):
        pass

    def show_login(self):
        self.login = Login()
        self.login_exist = 1
        self.login.setupUi(self.login)
        self.login.switch_window.connect(self.show_filters)
        self.login.show()

    def show_filters(self):
        if(self.filters_exist == 0):
            self.window = Filters()
            self.filters_exist = 1
            self.window.setupUi(self.window)
            self.window.switch_window.connect(self.show_result)
        if(self.result_exist == 1):
            self.result.close()
            self.result_exist = 0
        if(self.login_exist == 1):
            self.login.close()
            self.login_exist = 0
        self.window.show()
    
    def show_result(self, data):
        if(self.result_exist == 0):
            self.result = Result()
            self.result_exist = 1
            self.result.setupUi(self.result, data)
            self.result.switch_window.connect(self.show_filters)
            self.result.switch_window2.connect(self.show_details)
            self.window.hide()
        else:
            self.details.close()
            self.details_exist = 0
        self.result.show()

    def show_details(self, data):
        if(self.details_exist == 0):
            self.details_exist = 1
            self.details = Details_song()
            self.details.setupUi(self.details, data)
            self.details.switch_window.connect(self.show_result)
            self.details.switch_window2.connect(self.show_lyrics)
            self.result.hide()
        else: 
            self.lyrics.close()
        self.details.show()

    def show_lyrics(self, url):
        self.lyrics = Lyrics()
        self.lyrics.setupUi(self.lyrics, url)
        self.lyrics.switch_window.connect(self.show_details)
        self.details.hide()
        self.lyrics.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    controller = Controller()
    controller.show_login()
    sys.exit(app.exec_())